// Generates src/ui/icons.ts from the Material Design Icons set.
// Run once (npm run icons) and commit the result: the build and the shipped
// bundle never touch the network, so devices without internet get icons too.
// The icon list lives in icons.json - tailor it per device and regenerate.
import { readFileSync, writeFileSync } from "node:fs";

const { icons: NAMES }: { icons: string[] } = JSON.parse(
  readFileSync(new URL("../icons.json", import.meta.url), "utf8")
);

type IconifyMeta = { icons: Record<string, { body: string }> };

const res = await fetch(
  `https://api.iconify.design/mdi.json?icons=${NAMES.join(",")}`
);
if (!res.ok) throw new Error(`iconify API ${res.status}`);
const data = (await res.json()) as IconifyMeta;

const missing = NAMES.filter((n) => !data.icons[n]);
if (missing.length) throw new Error(`missing icons: ${missing.join(", ")}`);

const entries = Object.entries(data.icons)
  .map(([name, { body }]) => {
    const d = / d="([^"]+)"/.exec(body)?.[1];
    if (!d) throw new Error(`no path data for ${name}`);
    return `  "${name}": "${d}",`;
  })
  .join("\n");

const out = `// Generated by scripts/gen-icons.ts from icons.json - do not edit by hand.
// Keys omit the "mdi:" prefix; icon() in core/dom.ts strips it on lookup.
export const ICONS: Record<string, string> = {
${entries}
};
`;

writeFileSync(new URL("../src/ui/icons.ts", import.meta.url), out);
console.log(`wrote ${NAMES.length} icons`);

