# See here for image contents: https://github.com/devcontainers/images/tree/main/src/javascript-node
# Node 24 to match .nvmrc; vite 8 requires ^20.19.0 || >=22.12.0.
FROM mcr.microsoft.com/devcontainers/javascript-node:24-bookworm

ENV \
  DEBIAN_FRONTEND=noninteractive \
  DEVCONTAINER=true \
  PATH=$PATH:./node_modules/.bin
