#!/bin/bash
# Generate C++ header with both gzip and brotli compressed versions
# Usage: make_header.sh <output_dir> <header_name> <namespace> [version]

OUTPUT_DIR="$1"
HEADER_NAME="$2"
NAMESPACE="$3"
VERSION="$4"
OUTPUT_FILE="./$OUTPUT_DIR/$HEADER_NAME"

# Determine the correct GZIP define based on namespace
if [ "$NAMESPACE" = "captive_portal" ]; then
  GZIP_DEFINE="USE_CAPTIVE_PORTAL_GZIP"
elif [ "$NAMESPACE" = "web_server" ]; then
  GZIP_DEFINE="USE_WEBSERVER_GZIP"
else
  echo "Error: Unknown namespace '$NAMESPACE'. Expected 'captive_portal' or 'web_server'."
  exit 1
fi

# Verify both compressed versions exist (generated by vite)
if [ ! -f "$OUTPUT_DIR/index.html.gz" ] || [ ! -f "$OUTPUT_DIR/index.html.br" ]; then
  echo "Error: Both index.html.gz and index.html.br must exist in $OUTPUT_DIR"
  exit 1
fi

# Function to embed a compressed file as a C++ array
embed_compressed_file() {
  local input_file="$1"
  local array_name="$2"
  echo "const uint8_t ${array_name}[] PROGMEM = {" >>"$OUTPUT_FILE"
  xxd -cols 19 -i "$input_file" | sed -e '2,$!d' -e 's/^/    /' -e '$d' | sed -e '$d' | sed -e '$s/$/};/' >>"$OUTPUT_FILE"
}

cat <<EOT >"$OUTPUT_FILE"
#pragma once
// Generated from https://github.com/esphome/esphome-webserver

EOT

if [ -n "$VERSION" ]; then
  echo "#ifdef USE_WEBSERVER_LOCAL" >>"$OUTPUT_FILE"
  echo "#if USE_WEBSERVER_VERSION == $VERSION" >>"$OUTPUT_FILE"
  echo "" >>"$OUTPUT_FILE"
fi

cat <<EOT >>"$OUTPUT_FILE"
#include "esphome/core/hal.h"

namespace esphome::$NAMESPACE {

#ifdef $GZIP_DEFINE
EOT

embed_compressed_file "$OUTPUT_DIR/index.html.gz" "INDEX_GZ"

cat <<EOT >>"$OUTPUT_FILE"

#else  // Brotli (default, smaller)
EOT

embed_compressed_file "$OUTPUT_DIR/index.html.br" "INDEX_BR"

cat <<EOT >>"$OUTPUT_FILE"

// Backwards compatibility alias
#define INDEX_GZ INDEX_BR

#endif  // $GZIP_DEFINE

}  // namespace esphome::$NAMESPACE
EOT

if [ -n "$VERSION" ]; then
  echo "" >>"$OUTPUT_FILE"
  echo "#endif" >>"$OUTPUT_FILE"
  echo "#endif" >>"$OUTPUT_FILE"
fi
