#!/bin/bash
# Generate C++ header with both gzip and brotli compressed versions
# Usage: make_header.sh <output_dir> <header_name> <namespace> [version]

OUTPUT_DIR="$1"
HEADER_NAME="$2"
NAMESPACE="$3"
VERSION="$4"

# Determine the correct GZIP define based on namespace
if [ "$NAMESPACE" = "captive_portal" ]; then
  GZIP_DEFINE="USE_CAPTIVE_PORTAL_GZIP"
else
  GZIP_DEFINE="USE_WEBSERVER_GZIP"
fi

# Verify both compressed versions exist (generated by vite)
if [ ! -f "$OUTPUT_DIR/index.html.gz" ] || [ ! -f "$OUTPUT_DIR/index.html.br" ]; then
  echo "Error: Both index.html.gz and index.html.br must exist in $OUTPUT_DIR"
  exit 1
fi

cat <<EOT >./$OUTPUT_DIR/$HEADER_NAME
#pragma once
// Generated from https://github.com/esphome/esphome-webserver

EOT

if [ -n "$VERSION" ]; then
  echo "#ifdef USE_WEBSERVER_LOCAL" >>./$OUTPUT_DIR/$HEADER_NAME
  echo "#if USE_WEBSERVER_VERSION == $VERSION" >>./$OUTPUT_DIR/$HEADER_NAME
  echo "" >>./$OUTPUT_DIR/$HEADER_NAME
fi

cat <<EOT >>./$OUTPUT_DIR/$HEADER_NAME
#include "esphome/core/hal.h"

namespace esphome::$NAMESPACE {

#ifdef $GZIP_DEFINE
EOT

echo "const uint8_t INDEX_GZ[] PROGMEM = {" >>./$OUTPUT_DIR/$HEADER_NAME
xxd -cols 19 -i "$OUTPUT_DIR/index.html.gz" | sed -e '2,$!d' -e 's/^/    /' -e '$d' | sed -e '$d' | sed -e '$s/$/};/' >>./$OUTPUT_DIR/$HEADER_NAME

cat <<EOT >>./$OUTPUT_DIR/$HEADER_NAME

static constexpr size_t INDEX_SIZE = sizeof(INDEX_GZ);
static constexpr const char *INDEX_CONTENT_ENCODING = "gzip";

#else  // Brotli (default, smaller)
EOT

echo "const uint8_t INDEX_BR[] PROGMEM = {" >>./$OUTPUT_DIR/$HEADER_NAME
xxd -cols 19 -i "$OUTPUT_DIR/index.html.br" | sed -e '2,$!d' -e 's/^/    /' -e '$d' | sed -e '$d' | sed -e '$s/$/};/' >>./$OUTPUT_DIR/$HEADER_NAME

cat <<EOT >>./$OUTPUT_DIR/$HEADER_NAME

// Backwards compatibility alias
#define INDEX_GZ INDEX_BR
static constexpr size_t INDEX_SIZE = sizeof(INDEX_BR);
static constexpr const char *INDEX_CONTENT_ENCODING = "br";

#endif  // $GZIP_DEFINE

}  // namespace esphome::$NAMESPACE
EOT

if [ -n "$VERSION" ]; then
  echo "" >>./$OUTPUT_DIR/$HEADER_NAME
  echo "#endif" >>./$OUTPUT_DIR/$HEADER_NAME
  echo "#endif" >>./$OUTPUT_DIR/$HEADER_NAME
fi
