name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    permissions:
      contents: read
    uses: ./.github/workflows/build.yaml
